2022-12-05 09:19:26,022 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 09:19:37,055 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 09:19:47,482 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 09:19:55,042 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 09:20:39,779 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 09:20:54,643 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 09:44:34,124 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 10:00:29,804 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 10:04:45,074 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 10:19:31,956 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 10:28:16,894 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 10:56:06,153 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
2022-12-05 12:21:54,975 ERROR: Exception on /export_posts [GET] [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\main\routes.py", line 217, in export_posts
    current_user.launch_task('export_posts', _('Exporting posts...'))
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\models.py", line 148, in launch_task
    rq_job = current_app.task_queue.enqueue('app.tasks.' + name, self.id,
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\rq\queue.py", line 502, in enqueue
    return self.enqueue_call(
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\rq\queue.py", line 400, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\rq\queue.py", line 560, in enqueue_job
    job.save(pipeline=pipe)
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\rq\job.py", line 650, in save
    if self.get_redis_server_version() >= StrictVersion("4.0.0"):
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\rq\job.py", line 658, in get_redis_server_version
    self.redis_server_version = get_version(self.connection)
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\rq\utils.py", line 283, in get_version
    version_string = connection.info("server")["redis_version"]
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\redis\client.py", line 1306, in info
    return self.execute_command('INFO', section)
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "C:\Users\caram\source\repos\projects\school\CIS5800_pt2\venv\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to None:6379. No connection could be made because the target machine actively refused it.
2022-12-05 14:45:44,161 INFO: Microblog startup [in C:\Users\caram\source\repos\projects\school\CIS5800_pt2\app\__init__.py:86]
